### ISSUE TITLE
Pages surrounded by square brackets not linkable on Windows

### ISSUE THREAD

**Issue by danokeeffe** [janwillemb/Ema-Personal-Wiki#11]
Hi,
According to the documentation, surrounding a word with double square brackets should make it linkable (e.g. [[Projects]]). This works fine on Android, but for some reason it is not working in the Windows client. Links to pages with multiple camel case words work fine on Windows e.g. MyProjects. 

Would it be possible to get a fix or perhaps a suggestion of what might be causing the issue?

Thanks.
P.s. Great project otherwise!

**Comment by janwillemb** [comment]
Hi,
The windows app only supports the {curlybrackets} style.
Jan Willem
